---
language: c
dist: xenial

addons:
  apt:
    packages: [gettext, libreadline-dev, libncursesw5-dev, texinfo, install-info, autotools-dev]

compile:
  - clang
  - gcc

script:
  - ./autogen.sh
  - ./configure
  - make
