---
language: c
dist: xenial

addons:
  apt:
    packages: [gettext, autopoint, libreadline-dev, libncursesw5-dev, texinfo, autotools-dev]
  brew:
    packages: [autoconf, automake, libtool, autopoint, gettext, texinfo]

compile:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-5"]
      env: [MATRIX_EVAL="CC=gcc-5"]

    - os: linux
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-6"]
      env: [MATRIX_EVAL="CC=gcc-6"]

    - os: linux
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-7"]
      env: [MATRIX_EVAL="CC=gcc-7"]

    - os: linux
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-8"]
      env: [MATRIX_EVAL="CC=gcc-8"]

    - os: linux
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-5.0"]
          packages: ["clang-5.0"]
      env: [MATRIX_EVAL="CC=clang-5.0"]

    - os: linux
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-6.0"]
          packages: ["clang-6.0"]
      env: [MATRIX_EVAL="CC=clang-6.0"]

    - os: linux
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-7.0"]
          packages: ["clang-7.0"]
      env: [MATRIX_EVAL="CC=clang-7.0"]

    - os: linux
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-8.0"]
          packages: ["clang-8.0"]
      env: [MATRIX_EVAL="CC=clang-8.0"]

    - os: osx
      osx_image: "xcode8"
      env: [MATRIX_EVAL="brew install gcc && CC=gcc-7"]

    - os: osx
      osx_image: "xcode8"
      env: [MATRIX_EVAL="brew install gcc && CC=gcc-8"]


before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./autogen.sh
  - ./configure
  - make
