---
language: c
dist: xenial

addons:
  apt:
    packages: &pkg_apt
      - gettext
      - autopoint
      - libreadline-dev
      - libncursesw5-dev
      - texinfo
      - autotools-dev
      - autoconf-archive
  homebrew:
    packages: &pkg_brew
      - autoconf
      - autoconf-archive
      - automake
      - readline
      - libtool
      - gettext
      - texinfo

matrix:
  include:
    - name: "linux/gcc-5"
      os: linux
      compiler: "gcc-5"
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages:
            - *pkg_apt
            - "gcc-5"

    - name: "linux/gcc-6"
      os: linux
      compiler: "gcc-6"
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages:
            - *pkg_apt
            - "gcc-6"

    - name: "linux/gcc-7"
      os: linux
      compiler: "gcc-7"
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages:
            - *pkg_apt
            - "gcc-7"

    - name: "linux/gcc-8"
      os: linux
      compiler: "gcc-8"
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages:
            - *pkg_apt
            - "gcc-8"

    - name: "linux/clang-5"
      os: linux
      compiler: "clang-5.0"
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-5.0"]
          packages:
            - *pkg_apt
            - "clang-5.0"

    - name: "linux/clang-6"
      os: linux
      compiler: "clang-6.0"
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-6.0"]
          packages:
            - *pkg_apt
            - "clang-6.0"

    - name: "linux/clang-7"
      os: linux
      compiler: "clang-7"
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-7"]
          packages:
            - *pkg_apt
            - "clang-7"

    - name: "osx/xcode-9.4"
      os: osx
      osx_image: "xcode9.4"
      compiler: clang
      env: [ CONFIGOPTIONS="--with-readline=/usr/local/opt/readline/" ]
      addons:
        homebrew:
          packages:
            - *pkg_brew

    - name: "osx/xcode-10.1"
      os: osx
      osx_image: "xcode10.1"
      compiler: clang
      env: [ CONFIGOPTIONS="--with-readline=/usr/local/opt/readline/" ]
      addons:
        homebrew:
          packages:
            - *gettext

    - name: "osx/hb/gcc-5"
      os: osx
      compiler: "gcc-5"
      env: [ CONFIGOPTIONS="--with-readline=/usr/local/opt/readline/" ]
      addons:
        homebrew:
          packages:
            - *pkg_brew
            - "gcc@5"

    - name: "osx/hb/gcc-8"
      os: osx
      compiler: "gcc-8"
      env: [ CONFIGOPTIONS="--with-readline=/usr/local/opt/readline/" ]
      addons:
        homebrew:
          packages:
            - *pkg_apt
            - "gcc@8"

  allow_failures:
    - os: osx
      compiler: gcc-8

before_install:
  - "$CC --version"

before_script:
  - export PATH="/usr/local/opt/gettext/bin:$PATH"

script:
  - ./autogen.sh
  - "./configure $CONFIGOPTIONS"
  - make

after_failure:
  - "test -e config.log && cat config.log"
